services:
  - type: web
    name: isud-calendar
    env: python
    region: oregon
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        value: postgres://...
      - key: FLASK_DEBUG
        value: "false"
